### ISSUE TITLE
Script for linuxcontainers.org does not work for debian buster on Android 4.4

### ISSUE THREAD

**Issue by green-green-avk** [green-green-avk/build-libarchive-minitar-android#1]
From <https://github.com/green-green-avk/AnotherTerm/issues/17>

---

Hello,

I have a tablet with Android 4.4.2 that I want to use AnotherTerm on. AnotherTerm itself seems to run fine, but I have some issues with the install-linuxcontainers script. I followed the guide on [here](https://green-green-avk.github.io/AnotherTerm-docs/installing-linux-under-proot.html#main_content).

I tried to install the root filesystem for debian buster (I also tried debian bulseye, ubuntu, gentoo and those all fail with a similar error; alpine does work fine however).

The first issue was that the script failed on [line 362](https://github.com/green-green-avk/AnotherTerm-scripts/blob/2f4840fd08b0e04dc6ec6b06852f693287946413/install-linuxcontainers.sh#L362) because the folder `etc/profile.d` did not exist. This is easily remedied by adding a `mkdir -p etc/profile.d`.

The second issue is that there seems to be a problem with unpacking the root filesystem. I get the error `-25: 9: chdir() failure`. After the error, the script continues, but the terminals into the root file system immediately stop after being started. With certain root file systems I get an additional error `Pathname can't be converted from UTF-8 to current locale.`

Any ideas on what is going wrong and how it could be fixed?

thanks,
Ruben

---

I tried AnotherTerm with the script on my phone that runs Android 8.1 and there the script runs just fine for debian. So it seems to be related to Android 4.4.2.

I was happy to find your project because it still supports KitKat, so thanks for that.

I'll try to debug the script a bit more.

---

After further testing, I see that the problem is caused by minitar. It gives errors on hardlinks and these errors seem in turn to cause a lot of data to go missing in the unpacked root file system. This is what causes the `etc/profile.d` folder to be missing and is likely also the reason that the chroot terminal is not working.

---

I tried to use a manipulated root file system without the hardlinks and that archive is working fine.

So something must be wrong when treating the hardlinks. For extra information, the unpacked root file system looks like the following when the hardlinks are still there:
```
linuxcontainers-debian-buster
\_ etc
\_ usr
      \_bin
          \_usr
               \_bin
               \_games
               \_include
               \_local
               \_src
\_var
```

So, in the root folder I only get `etc`, `usr` and `var` and something weird is going on with the `usr` folder nested inside `usr/bin`.

**Comment by green-green-avk** [comment]
It seems, `openat()` system call has some specific behavior in old Androids...
However, `unlinkat()` seems available.

**Comment by green-green-avk** [comment]
Making `check_symlinks_fsobj()` in `archive_write_disk_posix.c` happy seems pretty enough.

**Comment by green-green-avk** [comment]
Should be fixed. Reopen in case of further problems. Beware of <https://github.com/green-green-avk/proot/issues/1#issuecomment-686794677>.

**Comment by rvdginste** [comment]
Just to confirm that it is working: I tested this with debian buster and bullseye and it's working just fine now.

Thanks!
